name: oulad_analytics
version: 1.0.0
config-version: 2

profile: oulad_analytics

model-paths: ["models"]
test-paths: ["tests/dbt"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

quoting:
  database: true
  schema: true
  identifier: false

models:
  oulad_analytics:
    mart:
      +schema: 03-mart
      +materialized: table
      +file_format: delta
